import type { ChannelName } from "./channelTypes";
import type { LocalePreference } from "./uiPrefs";

export const CHANNEL_LABELS: Record<ChannelName, Record<LocalePreference, string>> = {
  wechat: { zh: "微信", en: "WeChat" },
  feishu: { zh: "飞书", en: "Feishu" },
  dingtalk: { zh: "钉钉", en: "DingTalk" },
};

export function channelCopy(locale: LocalePreference) {
  return locale === "en"
    ? {
        intro: "Configure local message channels. Scan the WeChat QR code to connect.",
        config: "Configuration",
        runtime: "Runtime",
        access: "Authorized users",
        service: "Home service",
        enable: "Enable",
        disable: "Disable",
        reconnect: "Retry start",
        connectWechat: "Scan to connect",
        rebindWechat: "Scan again",
        connected: "WeChat is connected. You can send a message in WeChat now.",
        activating: "WeChat authorized. Starting the message service…",
        ready: "WeChat connected. You can send a message in WeChat now.",
        relogin: "WeChat login expired. Scan the QR code again.",
        refreshQr: "Refresh QR code",
        cancel: "Cancel",
        waiting: "Scan this QR code with WeChat, then confirm the login in WeChat.",
        scanned: "Scanned. Confirm the login in WeChat.",
        verify: "WeChat requires a verification code.",
        verifyCode: "Verification code",
        submit: "Verify",
        expired: "This QR code expired. Generate a new one.",
        succeeded: "WeChat authorized. Starting the message service…",
        publicId: "App ID",
        dingtalkId: "Client ID",
        secret: "App Secret",
        dingtalkSecret: "Client Secret",
        keepSecret: "Saved; leave blank to keep unchanged",
        unsetSecret: "Required on first save",
        saveConnect: "Save and connect",
        savedLocal:
          "The web UI writes secrets only to local secrets.toml and never returns them. The macOS CLI may use Keychain; on Windows, protection is the user-directory ACL, not POSIX 0600.",
        statusUnavailable: "Channel status unavailable",
        generatePair: "Generate pairing code",
        openConsole: "Open provider console",
        loading: "Loading channel state…",
        loadFailed: "Could not load channel state.",
        requiredId: "Enter the public ID.",
        requiredSecret: "Enter the secret for the first save.",
        noConfig: "Configure this channel before enabling it.",
        serviceDown: "The home service is not ready. Retry start to launch the adapter again.",
      }
    : {
        intro: "配置本机消息渠道。使用微信扫描二维码完成连接。",
        config: "配置",
        runtime: "运行状态",
        access: "已授权用户",
        service: "后台服务",
        enable: "启用",
        disable: "停用",
        reconnect: "重试启动",
        connectWechat: "扫码连接",
        rebindWechat: "重新扫码",
        connected: "微信已连接，现在可以在微信中发送消息。",
        activating: "微信授权成功，正在启动消息服务…",
        ready: "微信连接成功，现在可以在微信中发送消息。",
        relogin: "微信登录已过期，请重新扫码。",
        refreshQr: "刷新二维码",
        cancel: "取消",
        waiting: "请使用微信扫描二维码，然后在微信中确认登录。",
        scanned: "已扫码，请在微信中确认登录。",
        verify: "微信要求输入验证码。",
        verifyCode: "验证码",
        submit: "提交验证",
        expired: "二维码已过期，请重新生成。",
        succeeded: "微信授权成功，正在启动消息服务…",
        publicId: "App ID",
        dingtalkId: "Client ID",
        secret: "App Secret",
        dingtalkSecret: "Client Secret",
        keepSecret: "已保存，留空保持不变",
        unsetSecret: "首次保存时必填",
        saveConnect: "保存并连接",
        savedLocal:
          "网页只把密钥写入本机 secrets.toml，且不会回传。macOS 上 CLI 可能改用钥匙串；Windows 依赖用户目录 ACL，不等同于 POSIX 0600。",
        statusUnavailable: "渠道状态暂不可用",
        generatePair: "生成配对码",
        openConsole: "打开服务商控制台",
        loading: "正在加载渠道状态…",
        loadFailed: "无法读取渠道状态。",
        requiredId: "请输入公共 ID。",
        requiredSecret: "首次保存时请输入密钥。",
        noConfig: "请先配置该渠道，再启用。",
        serviceDown: "后台服务尚未就绪，可点击重试启动再次拉起适配器。",
      };
}

export type ChannelCopy = ReturnType<typeof channelCopy>;
