import type { LocalePreference } from "./uiPrefs";

const zh = {
  settings: "设置",
  closeSettings: "关闭设置",
  general: "通用",
  models: "模型",
  capability: "能力",
  personas: "学术人格",
  runtime: "运行与安全",
  skills: "技能与 MCP",
  advanced: "高级",
  interface: "界面",
  setupTitle: "开始使用 Omni",
  setupLead: "先配置主模型。视觉模型与 Semantic Scholar 可选，之后也能在设置里改。保存写入本机 ~/.omni，与 omni config 相同。",
  mainModel: "主模型",
  visionModel: "视觉模型（VLM）",
  semanticScholar: "Semantic Scholar",
  provider: "提供方",
  baseUrl: "接口地址",
  vlmEndpointHint: "和主模型一样：可填站点根或 /v1，会自动补上 /v1/chat/completions",
  modelName: "模型名",
  apiKey: "API 密钥",
  keepSecret: "已设置（留空保持不变）",
  unsetSecret: "未设置",
  optional: "可选",
  required: "必填",
  save: "保存",
  saving: "保存中…",
  test: "测试",
  testing: "测试中…",
  clearSecret: "清除密钥",
  useMock: "使用离线 mock",
  continue: "完成并继续",
  skipOptional: "可整段留空，不写盘。",
  mockHint: "离线 mock 不访问网络，之后可再换成真实模型。",
  saved: "已保存。当前网页的下一轮对话会使用新配置。已打开的 CLI REPL 或 omni serve 需重开。",
  paths: "配置路径",
  dataDir: "数据目录",
  changeHome: "更换数据目录",
  resetHome: "恢复默认 ~/.omni",
  homeWarn: "不会移动已有数据。更换后请重启 omni web。",
  embeddings: "嵌入召回",
  enable: "启用",
  disable: "关闭",
  remote: "远程 openai_compatible",
  specter2: "本地 SPECTER2",
  python: "Python 可执行文件",
  baseModel: "基座模型目录",
  adapter: "适配器目录",
  device: "设备",
  memoryEnabled: "记忆",
  cliDisplay: "CLI 显示（不影响网页外观）",
  uiMode: "UI 模式",
  verbosity: "详细程度",
  theme: "外观",
  language: "语言",
  themeSystem: "跟随系统",
  themeLight: "浅色",
  themeDark: "深色",
  langZh: "中文",
  langEn: "English",
  advancedHint: "任意点号键，等价于 omni config get / set / unset。",
  key: "键",
  value: "值",
  get: "读取",
  set: "写入",
  unset: "清除",
  effective: "有效配置",
  channels: "消息渠道",
  mcpAdd: "添加 MCP 服务器",
  mcpName: "名称",
  mcpCommand: "命令或 URL",
  remove: "移除",
  skillsTab: "技能",
  mcpTab: "MCP",
  skillSearch: "搜索技能",
  skillAdd: "添加本地技能",
  skillAddHint: "选择含 SKILL.md 的目录，导入到 ~/.omni/skills。默认隔离，阅读说明后再信任。",
  skillTrust: "信任",
  skillUntrust: "取消信任",
  skillRemove: "删除",
  skillTrustConfirm: "信任后，下一轮对话可以使用该技能。请先阅读说明和可执行文件。",
  skillRemoveConfirm: "将从 ~/.omni/skills 删除此技能。历史任务会保留。",
  skillConfirm: "确认",
  skillCancel: "取消",
  skillBuiltin: "内置",
  skillUser: "用户",
  skillQuarantined: "待审核",
  skillShadowed: "被遮蔽",
  skillTrusted: "已信任",
  skillEmpty: "没有匹配的技能",
  skillBody: "说明",
  skillKind: "类型",
  skillDelivery: "执行",
  skillPickDir: "选择技能目录",
  skillUseDir: "导入此目录",
  skillShowHidden: "显示隐藏",
  skillUp: "上一级",
  skillNotice: "已更新。当前网页的下一轮对话会重新发现技能。已打开的 CLI REPL 或 omni serve 需重开。",
  help: "与 omni config 同一套文件。网页只写本机 secrets.toml，不会回传密钥。macOS 上 CLI 可能改用钥匙串；Windows 依赖用户目录 ACL，不等同于 POSIX 0600。",
  setupIncomplete: "请选择 mock，或填写主模型的接口地址和模型名。",
  failed: "保存失败",
};

const en: typeof zh = {
  settings: "Settings",
  closeSettings: "Close settings",
  general: "General",
  models: "Models",
  capability: "Capabilities",
  personas: "Scientist personas",
  runtime: "Runtime & security",
  skills: "Skills & MCP",
  advanced: "Advanced",
  interface: "Interface",
  setupTitle: "Set up Omni",
  setupLead:
    "Configure the main model first. Vision and Semantic Scholar are optional and can be changed later. Saves go to ~/.omni — the same files as omni config.",
  mainModel: "Main model",
  visionModel: "Vision model (VLM)",
  semanticScholar: "Semantic Scholar",
  provider: "Provider",
  baseUrl: "Base URL",
  vlmEndpointHint: "Same as the main model: a site origin or /v1 base URL is expanded to chat/completions",
  modelName: "Model",
  apiKey: "API key",
  keepSecret: "Set (leave blank to keep)",
  unsetSecret: "Not set",
  optional: "Optional",
  required: "Required",
  save: "Save",
  saving: "Saving…",
  test: "Test",
  testing: "Testing…",
  clearSecret: "Clear key",
  useMock: "Use offline mock",
  continue: "Save and continue",
  skipOptional: "Leave blank to skip writing.",
  mockHint: "Mock stays offline. You can switch to a real model later.",
  saved:
    "Saved. The next turn in this web process uses the new settings. Restart an open CLI REPL or omni serve.",
  paths: "Config paths",
  dataDir: "Data directory",
  changeHome: "Change data directory",
  resetHome: "Restore default ~/.omni",
  homeWarn: "Existing data is not moved. Restart omni web after changing home.",
  embeddings: "Embedding recall",
  enable: "Enable",
  disable: "Disable",
  remote: "Remote openai_compatible",
  specter2: "Local SPECTER2",
  python: "Python executable",
  baseModel: "Base-model directory",
  adapter: "Adapter directory",
  device: "Device",
  memoryEnabled: "Memory",
  cliDisplay: "CLI display (not the web theme)",
  uiMode: "UI mode",
  verbosity: "Verbosity",
  theme: "Appearance",
  language: "Language",
  themeSystem: "System",
  themeLight: "Light",
  themeDark: "Dark",
  langZh: "中文",
  langEn: "English",
  advancedHint: "Any dotted key — the same as omni config get / set / unset.",
  key: "Key",
  value: "Value",
  get: "Get",
  set: "Set",
  unset: "Unset",
  effective: "Effective configuration",
  channels: "Message channels",
  mcpAdd: "Add MCP server",
  mcpName: "Name",
  mcpCommand: "Command or URL",
  remove: "Remove",
  skillsTab: "Skills",
  mcpTab: "MCP",
  skillSearch: "Search skills",
  skillAdd: "Add local skill",
  skillAddHint: "Choose a directory with SKILL.md. It is copied into ~/.omni/skills, quarantined until you review and trust it.",
  skillTrust: "Trust",
  skillUntrust: "Untrust",
  skillRemove: "Delete",
  skillTrustConfirm: "After trust, the next turn can use this skill. Read the instructions and executable files first.",
  skillRemoveConfirm: "This deletes the skill from ~/.omni/skills. Historical tasks are kept.",
  skillConfirm: "Confirm",
  skillCancel: "Cancel",
  skillBuiltin: "Built-in",
  skillUser: "User",
  skillQuarantined: "Quarantined",
  skillShadowed: "Shadowed",
  skillTrusted: "Trusted",
  skillEmpty: "No matching skills",
  skillBody: "Instructions",
  skillKind: "Kind",
  skillDelivery: "Delivery",
  skillPickDir: "Choose skill directory",
  skillUseDir: "Import this directory",
  skillShowHidden: "Show hidden",
  skillUp: "Parent directory",
  skillNotice: "Updated. The next turn in this web process rediscovers skills. Restart an open CLI REPL or omni serve.",
  help: "Same files as omni config. The web UI writes secrets only to local secrets.toml and never returns them. The macOS CLI may use Keychain; on Windows, protection is the user-directory ACL, not POSIX 0600.",
  setupIncomplete: "Choose mock, or fill in the main model URL and name.",
  failed: "Save failed",
};

export type SettingsCopy = typeof zh;

export function settingsCopy(locale: LocalePreference): SettingsCopy {
  return locale === "en" ? en : zh;
}
